services:
  cassandra:
    image: cassandra:5.0.9
    container_name: hmf-cassandra
    ports:
     - "9042:9042"
    volumes:
     - cassandra-data:/var/lib/cassandra

  postgresql:
    image: postgresql:17
    container_name: hmf-postgres
    
    environment:
      POSTGRES_USER: hmf
      POSTGRES_PASSWORD: hmfdev
      POSTGRES_DB: cloud_provider

    ports:
    - "5432:5432"

    volumes:
    - postgres-data:/var/lib/postgresql/data
    - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  cassandra-data:
  postgres-data: